// Auto-generated by start-local.sh — do not edit manually.
// Re-run start-local.sh to refresh the anon key after a restart.
window.SUPABASE_URL      = 'https://carneous-unsatirized-rylee.ngrok-free.dev';
window.SUPABASE_ANON_KEY = 'LOCAL_ANON_KEY_PLACEHOLDER';
